language: java
sudo: false
jdk:
- oraclejdk10
env:
  global:
  - secure: "EKWTN92R2QwWdSoWpbWuH7s97+G/ev8eVQFDJYyPDukaY7PxgYm1gJamBxqpYWwzAThSW190K2ZiBfsvvJ1BfxNZt2OJi7U3lWrFx7iosBnv19zayaj99+CJMJz4w9+lJO911wJrk9B7fFljLKPGtj5ARSNDAfWJjMnQJScx0b35G+vn6k+5370TCzr6MSQbhRaf3/smVih1x+e5V3rrs5sdE1nsQ4X3uxWAnftl73LInxTeDVVQJLBfw/g3CJdWT5BP+VgY8dtkD//bPJCMZnd5+G+GDM0swbhPmaRqCA8J4xk4juH91V8S465JLRvfJH3rkzu6c3BCtjqBqLVoWeq0b6AXBrQMp3WBib9ylEpnkQT8KU92VEoueXjHu1bFIzvhigyLM7Le944jK/7g3HeUNZOLD2kKcS34w+pxfttRy/pBXdIf4GvRZvgKJkj1wUo24kXkRbOqkryIIonUPi4kbZ/7SmVXhbCvNDCX/yf+coVsJAln2ZSCMTUVohLL3/Ry5f28U0RiowG2gB5fq/dzbdzF76chLHcuap4oHLOCRqrnduG2FWkeSgxVKKKxVc4g5ZT8UCwdMmqoSZF5BLgj/NwtQ+kxI0fX9FPjttymfoQ8pZ6bKT9kOBkUfdxjv6CfvaAppUAnNBx2AvPtepBDzc4JSuPqcRe2lDLQFFY=" # COVERITY_SCAN_TOKEN
  - secure: "I/yCjGHCtNMBezO2ylpKKXU1m/deYj3l7yBx/epXVFv9pPixzgMUaGaOxJrz3s82ZuigwYgcRUDgjx0lmKJCKJCM1IGESjxfDvJPvY+yAbQz1PUd9O+buHtNU1nZRHGrPSSlv9aeCzYCcOtcP3GPlrVAGXalOnpTNeA8tfjjFXRYRSFgybP9ENVyRuVdI4gL3wfJV1OEXQ+87WsgTSmaadQymJilphGRdbTgxP6rilZVc7OJOgFmfyE38oJObSUDo7rzU4pPYHQI8DPGOo6Q9il0HEcJ6Zrz77JLTbrjcVhe4jK1MV57AdB15YGpw8gWa6Mzr2sEKwDw+iJ5ONGgCgwJM4OrJI3swdZtDbttV2GGnMot8gVn/l9Et6SMn7s+GoLRdfltie2SWZy/Zej2VnAxSUQ9Ty2FlrpExPSPgUAkDpgWEe+HYh/wMCsOQyX0dPQdsyOeYMJHyHqooR0IkHq2JIhfxb90x3mplRCAi0CXT2MXHAVh1ymNcI56BIY6y1NWsToAgElFGGAh6ntqND82+SnEqZYs7eA0RQsYfd8E7utHVPeEi14sen/j+hV8pnkUwju5n/3oqaPoecuuR7vXAI6pm2m9XmZoxeDC5REmGNnLWc6AxkHzh6LNemni+1RCvNmX2ypQmy0WUt1iovxi7yXc+9gdpEWIbgQu5do=" # CODACY_PROJECT_TOKEN
  - secure: "J2u0PFVLT9pOUUoyNXHfCXWji33iJZlt9UwUzDA9B3zypHyiRfpMYvaZsHgqWF/VjrGqzRWIC3YgM3b0FbLb8GsYLFQ4ltELCCvy/dC/dZ2PwuXbAi4gK55csBOf3EvIE3SOfFqfM+ljpZIL88bjlcch+8uksCuoGxaMlQP0gpaeT+WEWZZG+FUml7ts7TVZMPANy/6uVOvtGrCFD42p56AVFNDDlyyIU5PdLkWLVG0Gd1WbOUSTzloq2pCb5fdcH5ib3bf91poKYkWKWnQTpvF5PoAbpGf6cJ7/Gk49bnsCRjF91T0yZ/ZFlT31S0IjnFKHdTzClAY87KfPJBdtkgrL2ejJRYIdE8qjID8a3W+KBY9iHDU9qwxIBLTfsCosYHOUNeUgBEKQLB0NFmsysSX/M3KQLpZYLd+A1e69v8PSEUowYXDJXqF3t6PEmq9RgPd3zpi5SfpSuZupq24sJoME49Ul4qpJk6bVL8BSYz6osZdCrCdSykmGM1C9+nf2WBmYOwi5a/+Mr1apmA+KEQpDoBSP2ztt8KkUM6px5CHjqwdqD09QD0d+4k+XHEWfj5RNnMaESGAgEAX/cUhJ+oqGF+9MdUBvGZ1f/f2mndMPmVDIenhmmSBrqby+7f3elH0oFKmUwQbiluaNMHDJTBuxzoZS4n6IDZNuaRrLP7E=" # BINTRAY_API_KEY
install:
- curl -o $HOME/.m2/settings.xml https://gist.githubusercontent.com/cryptobot/cf5fbd909c4782aaeeeb7c7f4a1a43da/raw/e60ee486e34ee0c79f89f947abe2c83b4290c6bb/settings.xml
- mvn source:help javadoc:help dependency:go-offline -Pdependency-check,coverage,release
before_script:
- mvn --update-snapshots dependency-check:check -Pdependency-check
script:
- mvn clean test jacoco:report verify -Pcoverage -Dorg.slf4j.simpleLogger.defaultLogLevel=debug
after_success:
- curl -o ~/codacy-coverage-reporter.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar
- $JAVA_HOME/bin/java -jar ~/codacy-coverage-reporter.jar report -l Java -r target/site/jacoco/jacoco.xml
cache:
  directories:
  - $HOME/.m2
addons:
  coverity_scan:
    project:
      name: "cryptomator/cryptolib"
      description: "Build submitted via Travis CI"
    notification_email: sebastian.stenzel@cryptomator.org
    build_command_prepend: "mvn clean"
    build_command: "mvn compile -DskipTests=true"
    branch_pattern: release.*
deploy:
- provider: script
  script: mvn clean versions:set -DnewVersion=${TRAVIS_TAG} deploy -DskipTests -Prelease
  skip_cleanup: true
  on:
    repo: cryptomator/cryptolib
    tags: true
after_deploy:
  - "echo '{\"close\": \"1\"}' | curl -X POST -u cryptobot:${BINTRAY_API_KEY} https://api.bintray.com/maven_central_sync/cryptomator/maven/cryptolib/versions/${TRAVIS_TAG}"